version: "3.7"

services:
  redis:
    container_name: web1Redis
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - TZ=Asia/Seoul

  mysql:
      image: mariadb:10
      container_name: web1Maria
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=muckpot_local
        - MYSQL_ROOT_PASSWORD=admin
        - TZ=Asia/Seoul
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./mariadata:/var/lib/maria
